// BANCO DE DADOS (POSTGRESQL)
CREATE DATABASE todo_api;

CREATE TABLE todos (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);